### ISSUE TITLE
Understanding KLLoss?

### ISSUE THREAD

**Issue by Prasanna1991** [Kaixhin/Autoencoders#3]
Hello,

Can you explain the way you calculated KLLoss in VAE? Isn't this a KL Divergence? 

Thanks.

**Comment by Kaixhin** [comment]
Yes this is just the KL divergence, and [Wikipedia](https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence#Kullback.E2.80.93Leibler_divergence_for_multivariate_normal_distributions) shows the general form for multivariate Gaussians, which can be simplified for the prior of N(0, 1). Unfortunately I'm not sure I'm able to give much more of an explanation, but perhaps the [Tutorial on Variational Autoencoders](https://arxiv.org/abs/1606.05908) will be helpful.

**Comment by Kaixhin** [comment]
Closing (due to a month of inactivity).
