### ISSUE TITLE
gradLoss from nn.criterion

### ISSUE THREAD

**Issue by haiyanyin** [Kaixhin/Autoencoders#5]
When I was running the code, I found that the sign of "gradLoss" from nn.criterion (main.lua, line 100) needs to be negated. 

Otherwise, the output of criterion:backward(xHat, x) (MSE for example) is giving "xHat-x" instead of "x-xHat".

**Comment by Kaixhin** [comment]
Not sure I see the issue? Looking at the source code of [MSECriterion](https://github.com/torch/nn/blob/master/MSECriterion.lua), the first input is the network output, and the second input is the target - which is the original network input in the case of autoencoders. I tried your way and only saw the loss blow up.

**Comment by haiyanyin** [comment]
It's my fault. Because I used the Rmsprop from original Atari to update the parameters, it is expecting "x-xHat", but the actual gradient should be "xHat-x". Thanks a lot for the response.
