### ISSUE TITLE
gradient of KL in CatVAE

### ISSUE THREAD

**Issue by Sunarker** [Kaixhin/Autoencoders#9]
Hi, kaixhin.
        Recently, I am reading your code for CatVAE and find that the gradients seems to be reverse. Is it right? Thanks

**Comment by Sunarker** [comment]
The line

local gradKLLoss = softmax:backward(Model.encoder.output:view(-1, Model.k), math.log(1 / Model.k) - logZ - 1):view(-1, Model.N * Model.k)

**Comment by Sunarker** [comment]
Should not be,

logZ + 1 - math.log(1/Model.k) ?

**Comment by Kaixhin** [comment]
Yes, this does seem like a mistake. Empirically, the samples come out much more diverse too, which is encouraging. Thanks for spotting!
